### ISSUE TITLE
feat: database integration

### ISSUE THREAD

**Issue by tomassasovsky** [tomassasovsky/radio-garden.dart#15]
We can use https://github.com/nyxx-discord/running_on_dart.git as a template, as it already has an implementation with PostgreSQL. They're using a custom-made migration tool, which can be found here: https://github.com/nyxx-discord/migent.git

**Comment by NazarenoCavazzon** [comment]
Saliendo con fritas rey

**Comment by tomassasovsky** [comment]
Hey 👋@NazarenoCavazzon!

Any updates on this?
